---
title: "M3.Ex1: Speech RAG"
format: html
---

Goal: implement RAG system on speech data.

Method: first convert from speech to text, then do simple text RAG.

A practical use case: [searchable meeting archives](https://docling-project.github.io/docling/usage/processing_audio_media/#a-practical-use-case-searchable-meeting-archives).

## Task 1: From Speech to Text (STT)

Step 1. Load YouTube Playlist.

- a playlist of YouTube videos (or one long)

Step 2. Run a transcription (STT) like OpenAI Whisper on the audio file to generate the text.

Note: if you run into problems with the STT model. Try a list of pdf/pptx presentations (or one long). When you finish the sub-sequent steps, you can get back to fix this one.

LangChain offers three integrations with YouTube:

- [~~YoutubeLoaderDL integration~~](https://docs.langchain.com/oss/python/integrations/document_loaders/yt_dlp) ([GitHub Issue](https://github.com/langchain-ai/docs/issues/3883))
- [YouTube audio integration](https://docs.langchain.com/oss/python/integrations/document_loaders/youtube_audio)
- [YouTube transcripts integration](https://docs.langchain.com/oss/python/integrations/document_loaders/youtube_transcript)

However, feel free to use any PyPi package, even if not listed in the LangChain integrations.

You might go for [Docling's ASR Pipeline](https://docling-project.github.io/docling/usage/processing_audio_media/) for For consistency with other pipeilines.

Want to go further with the exercise? Explore the [YouTube Data API](https://developers.google.com/youtube/v3).

## Task 2: Vector Store

Goal: Replace the `InMemoryVectorStore` in the previous RAG Pipeline with ChromaDB instead.

Step 1. Make persistent [ChromaDB](https://docs.trychroma.com/docs/overview/introduction) vector store on disk.

Step 2. Ingest the documents into the vector store.

Step 3. Query the documents by embeddings to find similar ones.

Step 4. Verify the database is kept when you restart the program, and that they embedding are not re-computed again.
