---
title: "Applied AI Bootcamp"
format: "html"
---

Welcome slides: [Introduction to Bootcamp](./W1/lessons/01_bootcamp_intro.qmd).

## Courses

- **Course 1: [Python](W1/)**
    Build strong Python programming foundations to apply and integrate ML/DL/AI in software systems.
- **Course 2: [Applied Data Science](W2/)**  
    Calculate, analyze, visualize, and interpret data. Then, formulate and test hypotheses.
- **Course 3: [Applied Machine Learning](W3/)**  
    Build reliable predictive modeling pipelines, debug its issues, evaluate and compare alternatives.
- **Course 4: [Agentic AI](W4/)**  
    Develop, debug, evaluate deploy, and monitor LLM-driven AI Agents to automate tasks involving unstructured data.
- **Course 5: [Applied Deep Learning](W5/)**  
    Use DL solution frameworks / libraries to apply AI to specific problems in NLP (language) and Computer Vision.
- **Course 6: [Agentic Engineering](W6/)**  
    Maximize the use of *Vibe Coding* via best practices to accelerate software development in your codebase.

**Estimated Duration**: 8 weeks.
