---
format: html
title: "Applied Machine Learning"
subtitle: "Building Predictive ML Pipelines with Scikit-learn"
mermaid-format: svg
toc-depth: 2
---

By the end of this course, you should be able to: 

1. Build **regression models** that use recorded data to estimate unknown data and make forecasts
1. Build **classifier models** that can inform decision making in medical and business settings
1. Build **reliable data pipelines** with robust pre-processing, post-processing with data quality and **privacy** in mind
1. Analyze various **modeling issues** and **data quality issues**, debug them, and avoid blind-spots that fail many practitioners silently
1. Apply **meta-learning** to search and automatically select the best model, from a set of models, for a given task
1. Apply XAI to **explain model predictions** and feature importance using general methods that apply to all types of predictive models

## Module 1: Linear Models

### M1-1: Introduction to ML

::: {.columns}
::: {.column}
Learning outcomes:

1. Define *Machine Learning* and understand its utility
1. Identify the two main tasks in *Supervised ML*
1. Identify the two parts of a *Data Matrix*
1. Distinguish *Features* from *Target*
1. Recognize foundations and related fields
1. Recognize the three main topics of ML
:::
::: {.column}
**Materials:**

- [🧬 Slides: Introduction](M1/lessons/01_slides_Intro_ML.qmd) (1 hour)
:::
:::
<!-- end columns -->

### M1-2: Linear Models

::: {.columns}
::: {.column}
Learning outcomes:

1. Given a DataFrame, split the feature columns from the target columns
1. Train a regressor (`LinearRegression`) model
1. Inspect the learned parameters of the model
1. Predict the target for any feature value
1. Plot the scatter plot and the regression line
1. Given a features-target split (X, y), further split it into train-test
1. Explain why we split data into train-test splits, and why the test set is held-out
1. Explain what the `stratify=target` parameter does
1. Train a classifier (`LogisticRegression`) model
1. Given a `DecisionBoundaryDisplay` distinguish between a classifier's `predict` and `predict_proba` methods
:::
::: {.column}
**Materials:**

- [🧬 Slides: Linear Models](M1/lessons/02_slides_linear_models.qmd) (45m)
- [🔬 Lab: Linear Models](M1/lessons/03_lab_linear_models.ipynb) (45m)

**Resources**:

- [https://scikit-learn.org/](https://scikit-learn.org/)

#### Exercises

- [✍️ Model Hours vs Marks](M1/exercises/ex1_reg.ipynb) (3hr)
- [✍️ Model Experience vs Salary](M1/exercises/ex2_reg.ipynb) (30m)
:::
:::
<!-- end columns -->

### M1-3: Non-linear Patterns

::: {.columns}
::: {.column}
Learning outcomes:

1. Distinguish between linear and non-linear relationships.
1. Fit non-linear patterns using linear models with `PolynomialFeatures`.
1. Fit non-linear patterns using linear models with `SplineTransformer`.
1. Fit non-linear patterns using non-linear models (Decision Tree).
:::
::: {.column}
**Materials:**

- [🧬 Slides: Non-linear patterns](M1/lessons/04_slides_non_linear_patterns.qmd) (25m)
- [🔬 Lab: Non-linear patterns](M1/lessons/05_lab_non_linear_patterns.ipynb) (15m)

#### Exercises

- [✍️ Iris Classification](M1/exercises/ex3_class.ipynb) (2hr)
- [✍️ Modeling Non-linear Patterns](M1/exercises/ex4_non-linear.ipynb) (30m)
:::
:::
<!-- end columns -->

## Module 2: Predictive Modeling Pipelines

Goal: Build a Pipeline to handle preprocessing of both categorical and numerical features.

::: {.columns}
::: {.column}
Learning outcomes:

1. Identify at least 2 causes of missing data
2. Apply `KNNImputer` to fill missing values; both numerical and categorical
3. Debug errors where `fit` and `transform` are misused on the wrong set of data
4. Explain the need for *Feature Scaling* in layman terms
5. Distinguish between linear and non-linear scaling methods
6. Identify when to use non-linear scaling
7. Given a scaled dataset, use `inverse_transform` to show their original values
8. Distinguish between `OrdinalEncoder` and `OneHotEncoder`
9. Understand the memory problem of one-hot encoding; and explain the solution
10. Recognize cases of data leakage
11. Explain how a scikit-learn `Pipeline` helps avoid data leakage
11. Recognize the function of each of: `fit`, `transform`, `predict`, and `score` methods
12. Use `ColumnTransformer` to build a mixed-type pipeline that can handle both numerical and categorical features

:::
::: {.column}
**Materials:**

1. [🔬 Lab: Handle Missing Values](M2/lessons/lab_impute.ipynb) (20m)
2. [🔬 Lab: Scaling: Numerical Features](M2/lessons/lab_scale.ipynb) (20m)
3. [🔬 Lab: Encoding: Cateogrical Features](M2/lessons/lab_encode.ipynb) (15m)
4. [🧬 Slides: Pipelines](M2/lessons/03_slides_pipeline.qmd) (20m)
5. [🔬 Lab: Pipelines](M2/lessons/04_lab_pipeline.ipynb) (10m)

#### Exercises

1. [✍️ Advertising Revenue](M2/exercises/ex1_multi-reg.ipynb) (1hr)
2. [✍️ Fuel Efficiency](M2/exercises/ex2_multi-reg.ipynb) (30m)

**Bonus**:

1. [Effect of rescaling on a k-neighbors models](M2/exercises/01_scaling_knn.ipynb) (30m)
2. [High-cardinality categorical features](M2/exercises/02_high-cardinality.ipynb) (20m)
:::
:::
<!-- end columns -->

## Module 3: Model Selection and Evaluation

### M3-1: Evaluation Metrics

::: {.columns}
::: {.column}

Learning outcomes:

In this lecture we learn to:

1. Detect *over-fitting* and *under-fitting* by estimating *generalization* performance
2. Establish a *baseline* for a model
3. Measure the *scalability* of the model
4. Identify other properties we need from a dataset besides quantity
5. Use *cross-validation* and explain it's inner-working
6. Recognize that a new model is instantiated for each train-validation score

:::
::: {.column}
**Materials:**

1. [🧬 Slides: Model Evaluation](M3/lessons/01_slides_evaluation.qmd) (30m)
2. [🔬 Lab: Cross-validation](M3/lessons/02_cross-validation.ipynb) (20m)

:::
:::
<!-- end columns -->

### M3-2: Hyper-parameter Tuning

::: {.columns}
::: {.column}

Learning outcomes:

1. Distinguish betweeen *parameters* and *hyper-parameters*
    1. Given linear regression model, identify it's *parameters* and *hyper-parameters*
    2. Given a decision tree model, identify it's *parameters* and *hyper-parameters*
2. Explain the full process of hyper-parameter search; describing the role of each of the 5 elements
3. Distinguish between Grid Search and Random Search

:::
::: {.column}
**Materials:**

- [🔬 Lab: Hyper-parameter Tuning](M3/lessons/03_hyper-parameter_tuning.ipynb) (30m)

**Extra:**

- [Text: Controlling Randomness](M3/texts/text_controlling_randomness.qmd)  
    Distinguish different cases to use `random_state` correctly to control randomness

:::
:::
<!-- end columns -->

## Module 4: Regression and Classification Metrics

### M4-1: Regression Metrics

::: {.columns}
::: {.column}
Learning outcomes:

1. Tell which of MAE and MSE are more sensitive to outliers and why
2. Recgonize the range of each of: $R^2$-score and MAPE; and interpret their results in layman terms for a specific business domain 
3. Interpret a *prediction plot* and a *residual plot*; and recognize what action could be taken from these plots
4. Explain when a *target transformation* may improve model fit and metrics.

:::
::: {.column}
**Materials:**

- [🧬 Slides: Regression Metrics](M4/lessons/01_slides_regression_metrics.qmd) (25m)
- [🔬 Lab: Evaluation of Regression Models](M4/lessons/02_lab_regression_metrics.ipynb) (20m)

:::
:::
<!-- end columns -->

### M4-2: Classification Metrics

::: {.columns}
::: {.column}
Learning outcomes:

1. Given a confusion matrix; tell the performance of a classifier
2. Given a PR-curve or ROC-curve; be able to tell which classifier is better
3. Distinguish between classification metrics on the basis of $FP$ (Precision) and $FN$ (Recall)
:::
::: {.column}
**Materials:**

- [🧬 Slides: Classification Metrics](M4/lessons/03_slides_classification_metrics.qmd) (30m)
- [🔬 Lab: Classification Metrics](M4/lessons/04_lab_classification_metrics.ipynb) (10m)
- [Widget: Classifier Threshold](M4/lessons/widget_threshold.qmd) (10m)
:::
:::
<!-- end columns -->


### M4-3: Classifier Threshold Tuning

::: {.columns}
::: {.column}
Learning outcomes:

1. Recognize the effect of moving the classifier threshold up and down
2. Given a classifier; tune the decision threshold to optimize a custom cost/objective function in terms of `FP:FN` ratio
:::
::: {.column}
**Materials:**

- [🔬 Lab: Classification Threshold Tuning](M4/lessons/06_lab_classifier_threshold_tuning.ipynb) (10m)
:::
:::

## Module 5: Decision Trees and Ensembles

### M5-1: Decision Trees


::: {.columns}
::: {.column}
Learning outcomes:

1. Recognize at least 1 advantage of decision trees (simple to explain)
2. Explain how decision trees work for regression (averaging)
3. Explain how decision trees work for classification (voting)
4. Explain how the maximum depth impacts generalization performance
:::
::: {.column}
**Materials:**

- [🧬 Slides: Decision Trees](M5/lessons/01_slides_trees.qmd) (15m)
- [🔬 Lab: Decision Trees](M5/lessons/02_lab_decision_trees.ipynb) (10m)
:::
:::

### M5-2: Ensemble Methods


::: {.columns}

::: {.column}

Learning outcomes:

1. Explain what an *Ensemble* is in layman terms
2. Describe the process of *Bagging* in layman terms
3. Describe the process of *Boosting* in layman terms
4. Recognize which of the two methods a Random Forest is an instance of
5. Identify at least 1 difference between *Bagging* and *Boosting*

:::

::: {.column}

**Materials:**

- [🧬 Slides: Bagging](M5/lessons/03_slides_bagging.qmd) (10m)
- [🧬 Slides: Boosting](M5/lessons/04_slides_boosting.qmd) (15m)
- [🔬 Lab: Ensembles](M5/lessons/05_lab_ensembles.ipynb) (20m)

:::

:::


## Module 6: Auto Machine Learning

**Materials:**

- [🧬 Slides: Auto ML with AutoGluon](M6/lessons/01_slides_auto_ml.qmd)

#### Exercises

- [✍️ Housing Prices Model](M6/exercises/ex1_pycaret_regression.ipynb)
- [✍️ Penguins Classification](M6/exercises/ex2_pycaret_classification.ipynb)

## Project

[**🎯 Machine Learning Project Details**](./Project/Project.qmd).

## References

- [CS129: Applied ML \| Standford](https://web.stanford.edu/class/cs129/syllabus)
- [Scikit-learn MOOC](https://inria.github.io/scikit-learn-mooc/)
- [Hands-on ML \| Aurélien Geron](https://github.com/ageron/handson-ml3)
- [Interpretable Machine Learning](https://christophm.github.io/)
