---
title: "Ex1: Models"
format: html
---

## Task 1: Text Generation Temperature

1. Setup an account at [OpenRouter.ai](https://openrouter.ai/)
2. Set the `OPENROUTER_API_KEY`
3. Select an LLM a free model like: `"nvidia/nemotron-3-nano-30b-a3b:free"`
4. make a high-temperature model and a low-temperature one
5. Ask both of them the same question and observe the answer
6. Include a stylistic instruction like "make it short" or "say it backwards" or "be poetic in your response" or "use only emojis"
7. Ask the model to format their answer as JSON

## Task 2: Sentiment Analysis

Step 1. Restrict the model to output exactly one of: `["positive", "neutral", "negative"]`.

Hint: Use `.with_structured_output()` with Pydantic's BaseModel subclass.

Step 2. Give the model a model few sentences, and observe it's output:

```text
# Positive
"Kindness creates lasting joy."
"Success rewards persistent effort."
"I love Sunlight. It warms the skin."

# Negative
"Pessemestic all the time."
"The storm caused damage!"

# Neutral
"The clock ticks steadily."
```

## Task 3: Categorization

Restrict the model to give tags (multi-output): `["cars", "shopping", "sports", "study", "work"]`.

try: 

```text
"That restoration looks incredible; you have a real talent for mechanics."
"I found the perfect gift today! The staff was incredibly helpful."
"Great game today! Your teamwork was the key to that victory."
"Learning together helped me finally grasp these concepts. Thank you!"
```

## Task 4: Data Extraction

Use `.with_structured_output()` to have a model read a resume/CV (text file) and identify key data points such as: Candidate Name, Skills, Experience, ..etc.

## Task 5: Tools

Step 1. Define 4 Python functions: `add(a, b)`, `subtract(a, b)`, `multiply(a, b)` and `divide(a, b)`.

Step 2. Copy those functions and place them in one multi-line string. like so:

```python
system_prompt = """
You are a math assistant. You have access to these tools:

def add(a, b):
    ...
...

Return the tool name and arguments required to solve the user's request.
"""
```

Step 3. Define the following pydanic class:

```py
class ToolCall(BaseModel):
    tool_name: str = Field(description="The name of the function to use")
    arguments: Dict[str, Any] = Field(description="The parameters to pass")
```

Step 4. Use structured output to ask the model to answer any mathematical question like: `"what is two plus 5"`

Observe: can you see what this could be used for? Can you extend this idea further?