---
title: "Applied Deep Learning"
subtitle: "Models, Data, Training, and Inference"
mermaid-format: svg
toc-depth: 2
format: 
  html:
    page-layout: full
---

## Topics

| \# | Lesson | Lab | Exercise |
|---------------|---------------|---------------|---------------|
| 1 | [Introduction to HuggingFace](M1/slides/01_Intro.qmd) | [Lab: Quick Tour](https://huggingface.co/docs/transformers/quicktour) | |
| 2 | [Transformers Pipelines](M1/slides/02_pipelines.qmd) | | |
| 3 | [Tasks (Docs)](https://huggingface.co/tasks) | [NLP Tasks](M1/slides/03_nlp_tasks.ipynb) ([♾️](https://colab.research.google.com/github/HassanAlgoz/B5/blob/main/content/W5/M1/slides/03_nlp_tasks.ipynb)) | |
| 4 | [Large and Small Language Models](M1/slides/05_llm_slm.qmd) | | |
| 5 | [Controlling LLM Generation](M1/slides/06_llm_generate.qmd) | [Lab](M1/slides/06_llm_generate_lab.ipynb) ([♾️](https://colab.research.google.com/github/HassanAlgoz/B5/blob/main/content/W5/M1/slides/06_llm_generate_lab.ipynb)) | |
| 6 | | [Audio Tasks](M1/slides/04_audio_tasks.ipynb) ([♾️](https://colab.research.google.com/github/HassanAlgoz/B5/blob/main/content/W5/M1/slides/04_audio_tasks.ipynb)) | |
| 7 | [Multi-modal Models](M1/slides/07_mutli-modal.ipynb) |  | |
| 8 |  |  | [Ex1: Data Curation with Label Studio](M1/slides/08_label_studio.qmd) |
| 9 | [Ultralytics YOLO Computer Vision Models](M1/slides/09_ultralytics.qmd) |  | |
| 10 | [Software Licenses](M1/slides/10_licensing.qmd) |  | |


## Learning end-goals

1. Use data to fine-tune foundation AI models
    - Data curation: what is labelled and which tech is used to label
    - Inference: speed, cost, performance metric
    - Fine-tuning time, cost, and performance tradeoff
2. Specify the technical requirements for AI integration
3. Make a decision matrix and select the most fit AI solution
4. Given a business process, evaluate the need for AI

## Bookmarks

- [HuggingChat](https://huggingface.co/chat/) for AI Assistance.
